Restructure hip common
GPUOpen-ProfessionalCompute-Libraries/rpp pull request #100
Opened 2022-03-29 04:00 UTC by r-abishek

@rrawther @asalmanp In this PR, all HIP functionalities were re-visited. New unions and structs have been used in hip to improve readability significantly with performance enhancements in certain variants.

@paveltc It affects code in all variants in Tensor HIP functionalities from ground up.

- Unions used are inspired from hip_vector_types.h and contain a data type ID to ensure the helpers are more intuitive
- The data type ID is:
    - ui1/ui2/ui3/ui4/ui6 for uint1/uint2/uint3/uint4/d_uint6
    - i1/i2/i3/i4/i6 for int1/int2/int3/int4/d_int6
    - f1/f2/f3/f4/f6/f8/f12/f16/f24 for float1/float2/float3/float4/d_float6/d_float8/d_float12/d_float16/d_float24
    - h1/h2/h3/h8/h24 for half/half2/hd_half8/d_half24 and others
- Every vector data type initialization in the hip common now has the specific format of variableNameInCamelCase_<one of the dataTypeID from above> for example srcPtr_f24 = float 24 type pointer or dstPtr_h8 = half 8 type pointer.
- Few other minor changes for argument reductions, removal of old typedef struct usage in gridmask, filters.
- It also adds performance improvements to certain filter type of functions - erode, dilate, box filter and a few other functionalities.

2022-04-01 04:11 UTC, paveltc commented
@r-abishek @asalmanp @rrawther I have run all of the relevant unit tests and checked them. Everything passes as expected.

2022-04-01 20:26 UTC, rrawther reviewed
@paveltc there are lots of changes in this PR which affects load and store of many kernels. It is hard to verify all of that looking at the code. Is there a way to compare the output in binary from previous version so we can make it didn't introduce any bugs

2022-04-04 18:01 UTC, paveltc commented
@rrawther The first thing that comes to mind is to do a binary compare of the images from this PR with known good images that were gotten previously.
I did, however, visually verify all of the image results for this PR and didn't see anything that was wrong.

2022-04-05 16:26 UTC, asalmanp reviewed
@r-abishek can you please check the remaining Codacy issues?

2022-04-05 17:03 UTC, r-abishek commented
@asalmanp I resolved most of them. There is only 1 pending:
- struct member 'd_schar8_s::sc1' is never used on L47 -> The custom type d_schar8_s is actually used in the next line L48

And secondly the only fix for the variable reassignment issue was to make an exception and change it to use the struct instead of the union in this commit -> https://github.com/GPUOpen-ProfessionalCompute-Libraries/rpp/pull/100/commits/0e4e22ab984cd7c968db7789ecf05b277f7ca0e1

2022-04-08 20:48 UTC, asalmanp approved these changes

2022-04-11 23:04 UTC, rrawther commented on src/include/hip/rpp_hip_common.hpp
> +typedef struct { d_schar8_s sc8[3];                                                             }   d_schar24_s;
This definition can cause confusion for the compiler. It might interpret it as 2dim array. Can you define it as schar xx[24] instead

2022-04-11 23:23 UTC, rrawther requested changes
@please fix the issue related to codacy warning

2022-04-11 23:49 UTC, rrawther approved these changes

2022-04-12 17:56 UTC, merged