MCW - RPP increase supported functionalities, test suite fixes
GPUOpen-ProfessionalCompute-Libraries/rpp pull request #45
Opened 2021-02-05 02:59 UTC by r-abishekmcw

- Add functionality support like water, glitch, resize mirror normalize, crop and patch, non linear blend, erase
- Update to a new interface to showcase supported functionalities in README
- Major test suite changes for compatibility with new functionalities
- Add basic hip functionality support for GPU functionalities
- OCL/HIP/HOST functionality bug fixes

2021-02-05 17:26 UTC, kiritigowda commented
@paveltc can you try these unit test updates? We need to verify if the unit test can be automated without any developer changes.

2021-02-05 21:55 UTC, paveltc commented
@kiritigowda and @rrawther I am running the tests now and seeing some problems. I have contacted Abishek regarding them.

2021-02-09 04:57 UTC, r-abishekmcw commented
@rrawther Almost all of the codacy warnings are now resolved. I'm finding it hard to resolve the few remaining ones that relate to calling python subprocess. I have tried using os.system or subprocess (with/without shell=True). Please let me know your thoughts on these few remaining codacy warnings.

2021-02-09 17:02 UTC, rrawther requested changes
There are quite a few changes in this PR. Tests need to pass performance and functionality before merging

2021-02-09 21:09 UTC, r-abishekmcw commented on utilities/rpp-performancetests/HIP_NEW/BatchPD_hip_pkd3.cpp
> +        outputFormatToggle = 0;
This is actually intentional since not all functions have this variant. I've highlighted on the email in more detail and mentioned it to Pavel too.

2021-02-09 21:10 UTC, r-abishekmcw commented on utilities/rpp-performancetests/HOST_NEW/BatchPD_host_pkd3.cpp
> +        outputFormatToggle = 0;
mentioned on email

2021-02-09 21:10 UTC, r-abishekmcw commented on utilities/rpp-performancetests/OCL_NEW/BatchPD_ocl_pkd3.cpp
> +    char funcName[1000];
mentioned on email

2021-02-09 21:10 UTC, r-abishekmcw commented on src/modules/cpu/host_fused_functions.hpp
> +                                *dstPtrTemp = (T) RPPPIXELCHECK(((Rpp32f)(*dstPtrCopyChannel) - mean) / stdDev);
Changed.

2021-02-09 21:15 UTC, r-abishekmcw commented on src/modules/cpu/host_fused_functions.hpp
> +
Removed

2021-02-16 17:23 UTC, rrawther commented
@paveltc : Any update on this? Are all the tests passing

2021-02-16 18:59 UTC, paveltc commented
@rrawther The only kernel that gives a seg fault is Integral in the HIP code. I can manually go through all of the images today and see if they look correct for CPU, OpenCL and HIP.

2021-02-16 19:33 UTC, paveltc commented
I am seeing an error with the Remap kernel in OpenCL:
Running remap_u8_BatchPD_OCL_PLN3_toPLN3.../tmp/comgr-e094ea/input/CompileSource:69:59: error: use of undeclared identifier 'max_width'
            IpixIdx = batch_index[id_z] + (id_x  + id_y * max_width[id_z] ) * plnpkdindex ;

2021-02-23 21:03 UTC, rrawther commented on src/modules/cl/cl_declarations.hpp
> -color_twist_cl_batch_tensor(cl_mem srcPtr, cl_mem dstPtr, rpp::Handle &handle, RPPTensorFunctionMetaData &tensor_info );
remove extra space at the end

2021-02-23 22:44 UTC, rrawther commented on src/modules/cl/kernel/non_linear_blend.cl
> +  res = 1 / (2 * pi * stdDev * std_dev);
this can be constant for all the threads, and hence better to precompute and pass it to kernel

2021-02-23 22:46 UTC, rrawther commented on src/modules/cl/kernel/non_linear_blend.cl
> +  if ((id_y >= yroi_begin[id_z]) && (id_y <= yroi_end[id_z]) &&
these has to be taken care when launching threads. Checking it in every kernel affect performance

2021-02-23 22:47 UTC, rrawther commented on src/modules/cl/kernel/non_linear_blend.cl
> +      output[pixIdx] = 0;
Rewrite the kernel to do at least 4 pixels and unroll the loop wherever possible

2021-02-23 23:36 UTC, rrawther commented on src/modules/cpu/host_advanced_augmentations.hpp
> +    for (int i = 0; i < bufferLength; i++)
Avoid extra copies for source and dest and have a separate kernel to work on the correct format

2021-03-12 17:42 UTC, rrawther commented on src/include/cpu/rpp_cpu_common.hpp
> +    // exp1 = exp1 + exp2;
remove commented lines from here

2021-03-12 17:55 UTC, rrawther commented on src/include/cpu/rpp_cpu_common.hpp
> +inline RppStatus generate_scharr_kernel_host(Rpp32f* kernel, Rpp32u type)
Looks like this function is not used anywhere? If so please remove it

2021-03-12 18:16 UTC, rrawther commented on src/modules/cl/cl_arithmetic_operations.cpp
> +// image_bit_depth_cl(cl_mem srcPtr, RppiSize srcSize, cl_mem dstPtr, RppConvertBitDepthMode convert_mode,
Why this is commented?

2021-03-15 18:18 UTC, rrawther requested changes
@paveltc : Please run all the unit tests with the latest changes from @r-abishekmcw

2021-03-22 16:59 UTC, kiritigowda commented
@paveltc & @rrawther  - can you verify the unit tests?

2021-03-22 21:25 UTC, rrawther commented
@paveltc : Did you do the final testing on this PR

2021-03-22 21:34 UTC, paveltc commented
@rrawther Yes,  I ran the tests last Thursday and so no new issues.

2021-03-22 23:13 UTC, rrawther approved these changes
@paveltc mentioned all the unit tests are passing.

2021-03-23 18:37 UTC, merged